In [1]:
print("hello ros2")

hello ros2


In [61]:
import rclpy
from rclpy.node import Node

rclpy.init()
node = Node("fs")
node.get_logger().info("hello, i'm fs.")
rclpy.spin(node)
rclpy.shutdown()

RuntimeError: Failed to init: rcl_init called on an already initialized context, at /tmp/binarydeb/ros-foxy-rcl-1.1.14/src/rcl/init.c:79

### Numpy

In [3]:
import numpy as np

In [2]:
!pip install numpy  -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 48.2 MB/s eta 0:00:00m eta 0:00:010:01


### 矩阵

In [6]:
# 3*3 单位矩阵
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# 3*3 零矩阵
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 随即矩阵
np.random.rand(3,3)

array([[0.89293139, 0.69889736, 0.15092628],
       [0.71154129, 0.0338613 , 0.09604417],
       [0.71261978, 0.53391065, 0.58814573]])

In [8]:
# 从数组创建矩阵
np.asarray([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [10]:
#  判断两个矩阵是否相等
print("零矩阵 & 单位矩阵 :", np.allclose(np.zeros([3,3]), np.identity(3)))

零矩阵 & 单位矩阵 : False


In [12]:
# 矩阵四则运算
A = np.asarray([1,2,3,4]).reshape(2,2)
B = np.zeros(2)
C = np.identity(2)
A_INV = np.linalg.inv(A)
print(np.add(A,B))
print(np.dot(A,B))
print(np.dot(A,C))
print(A_INV)
print(np.dot(A,A_INV))

[[1. 2.]
 [3. 4.]]
[0. 0.]
[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


> 需要注意的是，并不是所有的矩阵都有逆，比如零矩阵就没有逆，如果尝试用numpy来求逆则会出现错误

In [13]:
# 矩阵转置
A = np.asarray([1,2,3,4]).reshape(2,2)
A.T

array([[1, 3],
       [2, 4]])

## 空间描述

In [14]:
# 位置矩阵
# 3*1
np.asarray([1.0, 1.0, 1.0]).reshape(3,1)

array([[1.],
       [1.],
       [1.]])

In [18]:
# 姿态表示
# 姿态可以使用 3*3 的旋转矩阵表示，3*3 的单位矩阵没有姿态变换
# 新建一个旋转矩阵，表示绕着 z 轴旋转45度
import math
import numpy as np
theta = math.radians(45)
R_AB = np.asarray([math.cos(theta), -math.sin(theta), 0,
            math.sin(theta), math.cos(theta), 0,
            0, 0, 1
           ]).reshape(3,3)
print(R_AB)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [21]:
# 使用 numpy 求解矩阵 demo
import math 
import numpy as np
theta = math.radians(180)
R_BC = np.asarray([1, 0, 0,
                   0, math.cos(theta), -math.sin(theta),
                   0, math.sin(theta), math.cos(theta)]).reshape(3, 3)
R_BP = R_BC * np.identity(3)
print("旋转矩阵 R_BP: \n", R_BP)

旋转矩阵 R_BP: 
 [[ 1.  0.  0.]
 [ 0. -1. -0.]
 [ 0.  0. -1.]]


In [22]:
# 平移矩阵求解
P_BC = np.asarray([0, 0, 3]).reshape(3, 1)
P_CP = np.asarray([2, 1, 2]).reshape(3, 1)
P_BP = np.add(np.dot(R_BC, P_CP), P_BC)
print("位置矢量 P_BP: \n", P_BP.T)

位置矢量 P_BP: 
 [[ 2. -1.  1.]]


In [24]:
# 四元数转换
!pip install transforms3d -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 6.1 MB/s eta 0:00:00m eta 0:00:010:01:02
  Preparing metadata (setup.py) ... done
  Created wheel for transforms3d: filename=transforms3d-0.4.1-py3-none-any.whl size=1376757 sha256=51cd2fe256f429ab98ba65f9eba678085fa0c04c000141f2e46dfd05261d8e69
  Stored in directory: /home/htc/.cache/pip/wheels/99/e7/6c/d671676f152ff96168052a4960c6f8988d7e838823c3f039eb
Successfully built transforms3d


In [25]:
# 四元数 与 旋转矩阵 互转
import transforms3d as tfs
import numpy as np
# 四元数 转 旋转矩阵
tfs.quaternions.quat2mat([1, 0, 0, 0])
# 旋转矩阵 转 四元数
tfs.quaternions.mat2quat(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]))

array([1., 0., 0., 0.])

In [26]:
# 四元数 与 轴角 互转
import transforms3d as tfs
import numpy as np 
# 四元数转旋轴角
tfs.quaternions.quat2axangle([1,0,0,0])
# 轴角转四元数
tfs.quaternions.axangle2quat([1,0,0],0.5)

array([0.96891242, 0.24740396, 0.        , 0.        ])

In [27]:
# 欧拉角 与 四元数 互转
import transforms3d as tfs
import numpy as np 
# 固定轴欧拉角转四元数
tfs.euler.euler2quat(0,0,0,"sxyz")
# 四元数转固定轴欧拉角
tfs.euler.quat2euler([1,0,0,0],"sxyz")

(0.0, -0.0, 0.0)

In [29]:
# 欧拉角 与 旋转矩阵 互转
import transforms3d as tfs
import numpy as np 
# 固定轴欧拉角转旋转矩阵
tfs.euler.euler2mat(0,0,0,"sxyz")
# 旋转矩阵转固定轴欧拉角
tfs.euler.mat2euler(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]),"sxyz")

(0.0, -0.0, 0.0)

In [30]:
# 欧拉角 与 轴角互转
import transforms3d as tfs
import numpy as np 
# 固定轴欧拉角轴角
tfs.euler.euler2axangle(0,0,0,"sxyz")
# 轴角转固定轴欧拉角
tfs.euler.axangle2euler([1,0,0],0.5,"sxyz")

(0.5, -0.0, 0.0)

In [31]:
# 轴角相关转换
import transforms3d as tfs
import numpy as np 
# 轴角转旋转矩阵
tfs.axangles.axangle2mat([1,0,0],0.5)
# 旋转矩阵转轴角
tfs.axangles.mat2axangle(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]))

(array([0., 0., 1.]), 0.0)

In [33]:
# 齐次坐标变换
import numpy as np
import transforms3d as tfs
# 定义旋转矩阵R和平移向量T
R = np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]])
T = np.asarray([1,0,1])
R,T

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([1, 0, 1]))

In [34]:
# 使用numpy方法合成齐次变换矩阵
temp = np.hstack((R,T.reshape(3,1)))
np.vstack((temp,[0,0,0,1]))

array([[1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [35]:
# 使用tfs中的函数合成齐次变换矩阵
tfs.affines.compose(T,R,[1,1,1])

array([[1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [36]:
# 四元数+平移向量
# 先将四元数转换成旋转矩阵，然后再利用1.1合成齐次矩阵
R = tfs.quaternions.quat2mat([1,0,0,0])
tfs.affines.compose(T,R,[1,1,1])

array([[1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [1]:
# 静态广播发布器

import rclpy
from rclpy.node import Node

In [38]:
!ros2 interface show geometry_msgs/msg/TransformStamped

# This expresses a transform from coordinate frame header.frame_id
# to the coordinate frame child_frame_id at the time of header.stamp
#
# This message is mostly used by the
# <a href="https://index.ros.org/p/tf2/">tf2</a> package.
# See its documentation for more information.
#
# The child_frame_id is necessary in addition to the frame_id
# in the Header to communicate the full reference for the transform
# in a self contained message.

# The frame id in the header is used as the reference frame of this transform.
std_msgs/Header header

# The frame id of the child frame to which this transform points.
string child_frame_id

# Translation and rotation in 3-dimensions of child_frame_id from header.frame_id.
Transform transform


In [2]:
from geometry_msgs.msg import TransformStamped
# 从 tf2_ros 包中导入静态坐标变换广播器
from tf2_ros import StaticTransformBroadcaster

In [ ]:
# 初始化节点
rclpy.init()
node = Node("transform_node")
# 构造静态广播发布器
static_tf_pub = StaticTransformBroadcaster(node)
# 构造 TF 帧
t = TransformStamped()
t.header.stamp = node.get_clock().now().to_msg()
# parent-name 基坐标系B
t.header.frame_id = 'B'
# chrild-name 相机坐标系C
t.header.frame_id = 'C'
# 平移关系，单位 m
t.transform.translation.x = 0.0
t.transform.translation.y = 0.0
t.transform.translation.z = 3.0

t.transform.rotation.x = 0.0
t.transform.rotation.y = 0.0
t.transform.rotation.z = 0.0
t.transform.rotation.w = 0.0

In [ ]:
# 静态广播
# static_tf_pub.sendTransform(t)
# 10hz 发布坐标关系
def send_transfrom():
    t.header.stamp = node.get_lock().now().to_msg()
    tf.pub.sendTransform(t)
node.create_timer(0.1, send+transform)
rclpy.spin(node)

In [ ]:
!ros2 run tf2_ros tf2_echo B C